version: '3.9'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: campaign
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # persist data here
      
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local